# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN apt-get update && \
    apt-get install -y python sudo bash ca-certificates iproute2 systemd systemd-sysv python-pip \
                    libtool re2c libxml2-dev bzip2 libbz2-dev libzip-dev zlib1g zlib1g-dev libmariadb-dev libmagickwand-dev && \
    apt-get clean && \
    docker-php-ext-install zip \
        pcntl \
        mysqli \
        pdo_mysql \
        gd

