---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: nextclouddatabase
    groups:
      - nextclouddatabase_group
    image: ${DATABASE_MOLECULE_DISTRO:-debian:buster-slim}
    dockerfile: Dockerfile_database.j2
    privileged: true
    exposed_ports:
      - 3306/tcp
    published_ports:
      - 0.0.0.0:3306:3306/tcp
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    networks:
      - name: nextcloud
    purge_networks: yes
    stop_signal: 'RTMIN+3'

  - name: nextcloud
    groups:
      - nextcloud_group
    image: ${NEXTCLOUD_MOLECULE_DISTRO:-php:7.3-fpm-buster}
    dockerfile: Dockerfile_nextcloud.j2
    privileged: true
    # exposed_ports:
    #   - 80/tcp
    # published_ports:
    #   - 0.0.0.0:80:80/tcp
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    networks:
      - name: nextcloud
    purge_networks: yes
    stop_signal: 'RTMIN+3'
provisioner:
  name: ansible
verifier:
  name: ansible
